name: Upload HackTricks to HackTricks AI

on:
    workflow_dispatch:
    schedule:
    - cron: "0 5 1 * *"


jobs:
  dowload-clean-push:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # 1. Download the script
      - name: Dowload script
        run: wget "https://raw.githubusercontent.com/HackTricks-wiki/hacktricks-cloud/refs/heads/master/scripts/upload_ht_to_ai.py"

      - name: Install pip dependencies
        run: python3 -m pip install openai
        
      # 2. Execute the script
      - name: Execute script
        run: export MY_OPENAI_API_KEY=${{ secrets.MY_OPENAI_API_KEY }}; python3 "./upload_ht_to_ai.py"
