name: Upload HackTricks to HackTricks AI

on:
    workflow_dispatch:
    schedule:
    - cron: "0 5 1 * *"


jobs:
  dowload-clean-push:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      # 1. Download the script
      - name: Downlaods script
        run: wget "https://raw.githubusercontent.com/HackTricks-wiki/hacktricks-cloud/refs/heads/master/scripts/upload_ht_to_ai.py"

      - name: Install pip dependencies
        run: python3 -m pip install openai
        
      # 2. Execute the script
      - name: Downlaods script
        run: python3 "./upload_ht_to_ai.py"
